{:db-protocol "mysql"
 :db-name "//localhost:3306/demo?characterEncoding=UTF-8&serverTimezone=America/Los_Angeles"
 :database-url "mysql://localhost:3306/demo?user=root&password=Patito0257.&serverTimezone=America/Los_Angeles"
 :db-user "root"
 :db-pwd "Patito0257."
 :db-class "com.mysql.cj.jdbc.Driver"
 :email-host "smtp.fastmail.com"
 :email-user "hectorqlucero@fastmail.com"
 :email-pwd "h64k9rq89m7ba4ap"
 :port 3000
 :tz "US/Pacific"
 :company-name "Demo Company"
 :site-name "demo"
 :base-url "https://0.0.0.0:3000/"
 :uploads "./uploads/demo/"
 :img-url "https://0.0.0.0/uploads/"
 :path "/uploads/"}
